name: flutter_commons
description: Commons Flutter package can used for Flutter.
version: 0.0.1
homepage: https://github.com/cylyl/flutter_commons

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  common_utils: "^2.1.0"
  logger: "^2.1.0"
  flutter_udid: "^3.0.0"
  device_info_plus: ^9.0.0
  uuid: "^3.0.7"
  flustars: "^2.0.1"
  encrypt: ">=4.0.0 <6.0.0"
  advertising_id: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

